# docker build -t app:1.0 -f Dockerfile.1.0 \
#    --build-arg INSTALL_PHP_AMQP=true \
#    --build-arg INSTALL_PHP_MONGO=true \
#    --build-arg INSTALL_PHP_SWOOLE=true \
#    --build-arg INSTALL_PHP_DS=true \
#    --build-arg INSTALL_PHP_MEMINFO=true \
#    --build-arg INSTALL_PHP_SQLSRV=true \
#    .
FROM php:7.2-fpm

# Reset user to root to allow software install
# USER root

# If an ARG instruction has a default value and if there is no value passed at build-time, the builder uses the default.
ARG DEFAULT_USER=app
ARG DEFAULT_USER_UID=1001
# Unlike an ARG instruction, ENV values are always persisted in the built image.
ENV DEFAULT_USER ${DEFAULT_USER:-app}

ENV WORKDIR ${WORKDIR:-/var/www/app}

# Terminal
ENV TERM=xterm-256color \
    COLORTERM=truecolor

# Samples / Templates (Copy the content of samples to /home/USER inside the container)
COPY ./samples/bashrc /home/${DEFAULT_USER}/.bashrc
COPY ./samples/composer.json /home/${DEFAULT_USER}/.composer/

# Entrypoint
COPY ./docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

##################################
# Default php configurations values
##################################

# = /usr/local/etc/php (--with-config-file-path)
ENV PHP_INI_DIR ${PHP_INI_DIR:-/usr/local/etc/php}
# = /usr/local/etc/php/conf.d (--with-config-file-scan-dir)
ENV PHP_INI_SCAN_DIR ${PHP_INI_DIR}/conf.d
# Pool Definitions (docker.conf | www.conf | zz-docker.conf)
# /usr/local/etc/php-fpm.d/www.conf
ENV PHP_FPM_POOL_DIR ${PHP_INI_DIR}-fpm.d

###################################
# Package and dependency management
###################################

# PHP EXTRA BUILD dependencies
ENV PHP_EXTRA_BUILD_DEPS \
    sudo \
    gnupg \
    g++ \
    # @see https://github.com/alanxz/rabbitmq-c
    librabbitmq-dev \
    libgd-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxslt-dev \
    libgmp-dev \
    libtidy-dev \
    libxml2-dev \
    zlib1g-dev \
    libssl-dev

# Extra packages, common
ENV EXTRA_PACKAGES \
    git \
    openssh-client \
    zip \
    unzip \
    wget \
    vim

# Common installation parameters
ENV DEFAULT_PARAMETERS --no-install-recommends --no-install-suggests -y

#####
# PHP
#####
RUN set -eux && \
    apt-get update && \
    apt-get install ${DEFAULT_PARAMETERS} ${PHP_EXTRA_BUILD_DEPS} ${EXTRA_PACKAGES} && \
        ########
        # Configure PHP extensions
        ########
            docker-php-ext-configure gd \
                --with-gd \
                --with-jpeg-dir=/usr/include/ \
                --with-png-dir=/usr/include/ \
                --with-webp-dir=/usr/include/ && \
            docker-php-ext-configure mysqli --with-mysqli=mysqlnd && \
            docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd && \
            docker-php-ext-configure intl --enable-intl && \
        ########
        # Install PHP extensions
        ########
            docker-php-ext-install -j $(nproc) \
                mbstring \
                json \
                tokenizer \
                gettext \
                gd \
                bcmath \
                intl \
                gmp \
                pcntl \
                mysqli \
                pdo_mysql \
                soap \
                xsl \
                sockets \
                opcache \
                xml \
                zip && \
        # https://github.com/docker-library/php/issues/443
        pecl update-channels && \
        echo "---> Cleaning up" && \
        rm -rf /tmp/* ~/.pearrc && \
        apt-get clean -y && apt-get purge -y --autoremove && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /usr/share/man && \
        rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin && \
        echo "---> Remove files default PHP-FPM" && \
        rm ${PHP_INI_DIR}-fpm.conf.default && \
        rm ${PHP_FPM_POOL_DIR}/www.conf.default

RUN set -eux && \
    echo "---> Adding user to IMAGE" && \
    adduser --disabled-password --gecos '' --force-badname ${DEFAULT_USER} -u ${DEFAULT_USER_UID} && \
    echo "${DEFAULT_USER} ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers

########
## AMQP
# https://github.com/pdezwart/php-amqp
########
ARG INSTALL_PHP_AMQP=false
ENV PHP_AMQP_VERSION 1.9.3
RUN if [ ${INSTALL_PHP_AMQP} = true ]; then \
    pecl install amqp-${PHP_AMQP_VERSION} && \
    docker-php-ext-enable amqp \
;fi

########
## MONGODB
# https://docs.mongodb.com/php-library/current
# https://github.com/mongodb/mongo-php-library && composer require mongodb/mongodb
########
ARG INSTALL_PHP_MONGO=false
ENV PHP_MONGO_VERSION 1.5.1
RUN if [ ${INSTALL_PHP_MONGO} = true ]; then \
    pecl install mongodb-${PHP_MONGO_VERSION} && \
    docker-php-ext-enable mongodb \
;fi

########
## IGBINARY
########
ARG INSTALL_PHP_IGBINARY=true
ENV PHP_IGBINARY_VERSION 2.0.7
RUN if [ ${INSTALL_PHP_IGBINARY} = true ]; then \
    pecl install igbinary-${PHP_IGBINARY_VERSION} && \
    docker-php-ext-enable igbinary \
;fi

####
## LZF
####
ARG INSTALL_PHP_LZF=true
RUN if [ ${INSTALL_PHP_LZF} = true ]; then \
    pecl install lzf && \
    docker-php-ext-enable lzf \
;fi

########
## REDIS
# https://github.com/phpredis/phpredis
########
ARG INSTALL_PHP_REDIS=true
ENV PHP_REDIS_VERSION 4.1.0
RUN if [ ${INSTALL_PHP_REDIS} = true ]; then \
    printf "yes \n no \n" | pecl install -o -f redis-${PHP_REDIS_VERSION} && \
    docker-php-ext-enable redis \
;fi

########
## SWOOLE
# https://github.com/swoole/swoole-src
########
# RUN apt-get update && apt-get install ${DEFAULT_PARAMETERS} openssl libnghttp2-dev
# ARG INSTALL_PHP_SWOOLE=false
# ENV PHP_SWOOLE_VERSION 4.0.2
# RUN if [ ${INSTALL_PHP_SWOOLE} = true ]; then \
#     printf "yes \n yes \n yes \n yes \n yes \n yes \n no \n" | pecl install swoole-${PHP_SWOOLE_VERSION} && \
#     docker-php-ext-enable swoole \
# ;fi

########
## DATA STRUCTURES (DS)
# Data Structures (https://medium.com/p/9dda7af674cd)
# https://github.com/php-ds/extension
########
ARG INSTALL_PHP_DS=false
ENV PHP_DS_VERSION 1.2.6
RUN if [ ${INSTALL_PHP_DS} = true ]; then \
    pecl install ds-${PHP_DS_VERSION} && \
    docker-php-ext-enable ds \
;fi

########
## PHP MEMINFO
# https://github.com/BitOne/php-meminfo
########
ARG INSTALL_PHP_MEMINFO=false
ENV PHP_MEMINFO_VERSION v1.0.1
RUN if [ ${INSTALL_PHP_MEMINFO} = true ]; then \
    FILE='/tmp/php-meminfo.tar.gz'; \
    FOLDER='/tmp/php-meminfo'; \
    curl -L -o $FILE "https://github.com/BitOne/php-meminfo/archive/${PHP_MEMINFO_VERSION}.tar.gz" && \
    mkdir -p $FOLDER && tar -C $FOLDER -zxvf $FILE --strip 1 && \
    docker-php-ext-configure "$FOLDER/extension/php7/" --enable-meminfo && \
    docker-php-ext-install "$FOLDER/extension/php7/" && \
    rm -rf /tmp/* \
;fi

##############################
# SQLSRV + PDO_SQLSRV
# + ODBC Driver for SQL Server
##############################

# Microsoft Drivers for PHP for SQL Server (SQLSRV + PDO_SQLSRV)
# https://pecl.php.net/package/sqlsrv
# https://pecl.php.net/package/pdo_sqlsrv

ARG INSTALL_PHP_SQLSRV=false
ENV PHP_SQLSRV_VERSION 5.2.0
RUN if [ ${INSTALL_PHP_SQLSRV} = true ]; then \
    apt-get update -yqq && apt-get install ${DEFAULT_PARAMETERS} apt-transport-https && \
    # Installing the Microsoft ODBC Driver for SQL Server on Linux (DEBIAN)
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add - && \
    curl https://packages.microsoft.com/config/debian/9/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update -yqq && \
    # @see https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server#debian-8-and-9
    ACCEPT_EULA=Y apt-get install msodbcsql17 ${DEFAULT_PARAMETERS} && \
    # optional: for bcp and sqlcmd
    # ACCEPT_EULA=Y apt-get install mssql-tools && \
    # echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
    # echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
    # source ~/.bashrc
    # optional: for unixODBC development headers
    apt-get install unixodbc-dev ${DEFAULT_PARAMETERS} && \
    ## SQLSRV + PDO_SQLSRV
    pecl install sqlsrv-${PHP_SQLSRV_VERSION} pdo_sqlsrv-${PHP_SQLSRV_VERSION} && \
    docker-php-ext-enable sqlsrv pdo_sqlsrv \
;fi

# sudo tee /etc/php/7.2/mods-available/sqlsrv.ini >/dev/null <<EOF
#     extension=sqlsrv.so
#     extension=pdo_sqlsrv.so
# EOF
#
# ln -s /etc/php/7.2/mods-available/sqlsrv.ini /etc/php/7.2/fpm/conf.d/20-sqlsrv.ini
# ln -s /etc/php/7.2/mods-available/sqlsrv.ini /etc/php/7.2/cli/conf.d/20-sqlsrv.ini
#
# sudo echo "extension= pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
# sudo echo "extension= sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

################
# CONFIGURATIONS
################

# EXTENSIONS
# COPY ./config/extensions/xdebug.ini ${PHP_INI_SCAN_DIR}/docker-php-ext-xdebug.ini
# COPY ./config/extensions/opcache.ini ${PHP_INI_SCAN_DIR}/docker-php-ext-opcache.ini

# PHP-FPM
COPY ./config/fpm/php-fpm.conf ${PHP_INI_DIR}-fpm.conf
# PHP-FPM-POOL-WWW
COPY ./config/fpm/www.conf ${PHP_FPM_POOL_DIR}/www.conf
# PHP-INI
COPY ./config/php.ini-production.ini ${PHP_INI_DIR}/php.ini

# Allows server env (from docker-compose or cloudformation)
# to be available via dotEnv (and $_SERVER) in php-fpm.
# RUN sed -e 's/;clear_env = no/clear_env = no/' -i ${PHP_FPM_POOL_DIR}/www.conf

# Verify PHP
RUN set -x && \
    /usr/local/sbin/php-fpm --test && \
    PHP_ERROR="$( php -v 2>&1 1>/dev/null )" && \
    if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi

# Forward request and error logs to docker log collector
# RUN ln -sf /dev/stdout /var/log/php-fpm/access.log && \
#     ln -sf /dev/stderr /var/log/php-fpm/error.log

RUN set -eux && \
    echo "---> Changing permissions" && \
    mkdir -p ${WORKDIR} && \
    chown -R ${DEFAULT_USER}:${DEFAULT_USER} /var/www && \
    chown -R ${DEFAULT_USER}:${DEFAULT_USER} /usr/local/lib/php && \
    chown -R ${DEFAULT_USER}:${DEFAULT_USER} /home/${DEFAULT_USER}

####
# Node.JS
####
RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install nodejs -y
RUN npm install npm@6.1.0 -g
RUN npm install pm2 -g

RUN command -v node
RUN command -v npm
RUN command -v pm2

# Define the running user
USER ${DEFAULT_USER}

#####
# COMPOSER
#####

RUN set -x && \
    curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer && \
    composer global install --prefer-dist --no-dev --no-suggest --optimize-autoloader && \
    composer clear-cache

####
# PHPUnit
####
RUN wget https://phar.phpunit.de/phpunit.phar
RUN chmod +x phpunit.phar
RUN sudo mv phpunit.phar /usr/local/bin/phpunit
RUN command -v phpunit

# Application directory
WORKDIR "$WORKDIR"

# Environment variables
ENV PATH="$PATH:/home/${DEFAULT_USER}/.composer/vendor/bin"

# Display versions installed
RUN php -v
RUN composer --version
RUN phpunit --version
RUN node -v
RUN npm -v
RUN pm2 -v

############
# Entrypoint
############

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 9000 9099

CMD ["/usr/local/sbin/php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "--allow-to-run-as-root", "--nodaemonize"]
